name: Build README

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python build.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "chanthinker@foxmail.com"
        git config --global user.name "testdog-bot"
        git pull
        git add -A
        git commit -m "Updated content from bot" || exit 0
        git push
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    # - name: Build Project Artifacts
    #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy to Vercel
      run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}